/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLProduct.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   product/v1
// Description:
//   This is an API

#import "GTLProductCollection.h"
#import "GTLProductKey.h"
#import "GTLProductProduct.h"

#import "GTLQueryProduct.h"
#import "GTLServiceProduct.h"
