/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLProductProduct.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   product/v1
// Description:
//   This is an API
// Classes:
//   GTLProductProduct (0 custom class methods, 6 custom properties)

#import "GTLProductProduct.h"

// ----------------------------------------------------------------------------
//
//   GTLProductProduct
//

@implementation GTLProductProduct
@dynamic imageUrl, key, priceTime100, productDiscription, productName, upcCode;
@end
