/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLProductProduct.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   product/v1
// Description:
//   This is an API
// Classes:
//   GTLProductProduct (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLProductProduct
//

@interface GTLProductProduct : GTLObject
@property (copy) NSString *imageUrl;
@property (copy) NSString *key;
@property (retain) NSNumber *priceTime100;  // intValue
@property (copy) NSString *productDiscription;
@property (copy) NSString *productName;
@property (copy) NSString *upcCode;
@end
