/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLQueryUseritems.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   useritems/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryUseritems (3 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQueryUseritems : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (assign) long long desired;
@property (assign) long long have;
@property (copy) NSString *productKey;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryUseritems object.

// Method: useritems.delete
+ (id)queryForDeleteWithProductKey:(NSString *)productKey;

// Method: useritems.list
// Fetches a GTLUseritemsDesiredItemCollection.
+ (id)queryForList;

// Method: useritems.upsert
// Fetches a GTLUseritemsDesiredItem.
+ (id)queryForUpsertWithProductKey:(NSString *)productKey
                           desired:(long long)desired
                              have:(long long)have;

@end
