/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLQueryProduct.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   product/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryProduct (6 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLProductProduct;

@interface GTLQueryProduct : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (copy) NSString *identifier;
@property (copy) NSString *imageUrl;
@property (copy) NSString *key;
@property (copy) NSString *name;
@property (assign) NSInteger priceTime100;
@property (copy) NSString *productDiscription;
@property (copy) NSString *productName;
@property (copy) NSString *upc;
@property (copy) NSString *upcCode;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryProduct object.

// Method: product.get
// Fetches a GTLProductProduct.
+ (id)queryForGetWithIdentifier:(NSString *)identifier;

// Method: product.insert
// Fetches a GTLProductProduct.
+ (id)queryForInsertWithObject:(GTLProductProduct *)object;

// Method: product.patch
//  Optional:
//   imageUrl: NSString
//   key: NSString
//   priceTime100: NSInteger
//   productDiscription: NSString
//   productName: NSString
//   upcCode: NSString
// Fetches a GTLProductProduct.
+ (id)queryForPatchWithIdentifier:(NSString *)identifier;

#pragma mark -
#pragma mark "search" methods
// These create a GTLQueryProduct object.

// Method: product.search.name
// Fetches a GTLProductCollection.
+ (id)queryForSearchNameWithName:(NSString *)name;

// Method: product.search.upc
// Fetches a GTLProductCollection.
+ (id)queryForSearchUpcWithUpc:(NSString *)upc;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryProduct object.

// Method: product.update
// Fetches a GTLProductProduct.
+ (id)queryForUpdateWithObject:(GTLProductProduct *)object;

@end
