/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLUseritemsDesiredItemCollection.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   useritems/v1
// Description:
//   This is an API
// Classes:
//   GTLUseritemsDesiredItemCollection (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLUseritemsDesiredItem;

// ----------------------------------------------------------------------------
//
//   GTLUseritemsDesiredItemCollection
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLUseritemsDesiredItemCollection : GTLCollectionObject
@property (retain) NSArray *items;  // of GTLUseritemsDesiredItem
@end
