/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLUseritemsDesiredItem.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   useritems/v1
// Description:
//   This is an API
// Classes:
//   GTLUseritemsDesiredItem (0 custom class methods, 5 custom properties)

#import "GTLUseritemsDesiredItem.h"

#import "GTLUseritemsKey.h"

// ----------------------------------------------------------------------------
//
//   GTLUseritemsDesiredItem
//

@implementation GTLUseritemsDesiredItem
@dynamic desired, key, owned, productKey, userId;
@end
