/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLUseritems_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   useritems/v1
// Description:
//   This is an API

#import "GTLUseritemsDesiredItem.m"
#import "GTLUseritemsDesiredItemCollection.m"

#import "GTLQueryUseritems.m"
#import "GTLServiceUseritems.m"
