/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLUseritems.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   useritems/v1
// Description:
//   This is an API

#import "GTLUseritemsDesiredItem.h"
#import "GTLUseritemsDesiredItemCollection.h"
#import "GTLUseritemsKey.h"

#import "GTLQueryUseritems.h"
#import "GTLServiceUseritems.h"
