/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLUseritemsDesiredItem.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   useritems/v1
// Description:
//   This is an API
// Classes:
//   GTLUseritemsDesiredItem (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLUseritemsDesiredItem
//

@interface GTLUseritemsDesiredItem : GTLObject
@property (retain) NSNumber *desired;  // longLongValue
@property (copy) NSString *key;
@property (retain) NSNumber *owned;  // longLongValue
@property (copy) NSString *productKey;
@property (copy) NSString *userId;
@end
