/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLProductCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   product/v1
// Description:
//   This is an API
// Classes:
//   GTLProductCollection (0 custom class methods, 1 custom properties)

#import "GTLProductCollection.h"

#import "GTLProductProduct.h"

// ----------------------------------------------------------------------------
//
//   GTLProductCollection
//

@implementation GTLProductCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLProductProduct class]
                                forKey:@"items"];
  return map;
}

@end
