/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLProduct_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   product/v1
// Description:
//   This is an API

/*
#import "GTLProductCollection.m"
#import "GTLProductKey.m"
#import "GTLProductProduct.m"

#import "GTLQueryProduct.m"
#import "GTLServiceProduct.m"
*/
