/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLUseritemsDesiredItemCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   useritems/v1
// Description:
//   This is an API
// Classes:
//   GTLUseritemsDesiredItemCollection (0 custom class methods, 1 custom properties)

#import "GTLUseritemsDesiredItemCollection.h"

#import "GTLUseritemsDesiredItem.h"

// ----------------------------------------------------------------------------
//
//   GTLUseritemsDesiredItemCollection
//

@implementation GTLUseritemsDesiredItemCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLUseritemsDesiredItem class]
                                forKey:@"items"];
  return map;
}

@end
